# Generated by Django 5.0.1 on 2024-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_serviceuser_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceuser",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
